from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping, Protocol
from uuid import UUID

from .models import (
    ArtifactRef, CanonicalSnapshot, ChangeSet, CommitResult, ExecutionCommand,
    ExecutionRecord, LeaseClaim, MaterializationSpec, ProjectExecutionResult,
    ProjectWorkspaceState, StoredArtifact,
)


class CloudRuntimeError(RuntimeError): pass
class VersionConflict(CloudRuntimeError): pass
class LeaseConflict(CloudRuntimeError): pass
class ProjectIsolationError(CloudRuntimeError): pass
class ImmutableArtifactConflict(CloudRuntimeError): pass


class ControlStore(Protocol):
    def load_execution(self, execution_id: UUID) -> ExecutionRecord: ...
    def start_execution(self, execution_id: UUID, owner: str, lease_seconds: int) -> LeaseClaim | None: ...
    def renew_execution(self, execution_id: UUID, owner: str, fence_token: int, lease_seconds: int) -> LeaseClaim: ...
    def claim_resource(self, project_id: str, resource_key: str, execution_id: UUID, lease_seconds: int) -> LeaseClaim: ...
    def load_snapshot(self, project_id: str, spec: MaterializationSpec) -> CanonicalSnapshot: ...
    def commit_changes(self, command: ExecutionCommand, changes: ChangeSet, *, execution_fence: int, resource_fence: int | None, lease_owner: str | None = None, proposed_revision_id: UUID | None = None) -> CommitResult: ...
    def finish_execution(self, execution_id: UUID, fence_token: int, outcome: str, error: Mapping[str, Any] | None = None) -> None: ...


class ArtifactStore(Protocol):
    def download(self, project_id: str, artifact: ArtifactRef, destination: Path) -> None: ...
    def put_immutable(self, project_id: str, key: str, source: Path, expected_sha256: str) -> StoredArtifact: ...


class ProjectWorkspaceAdapter(Protocol):
    def materialization_spec(self, command: ExecutionCommand) -> MaterializationSpec: ...
    def resource_key(self, command: ExecutionCommand, snapshot: CanonicalSnapshot) -> str | None: ...
    def materialize(self, command: ExecutionCommand, snapshot: CanonicalSnapshot, workspace: Any, artifacts: ArtifactStore) -> ProjectWorkspaceState: ...
    def execute(self, command: ExecutionCommand, state: ProjectWorkspaceState) -> ProjectExecutionResult: ...
    def collect(self, command: ExecutionCommand, state: ProjectWorkspaceState, before: CanonicalSnapshot) -> ChangeSet: ...
